version: 2
jobs:
  build:

    docker:
      - image: cimg/openjdk:17.0

    steps:
      - checkout
      - run:
          name: Added execution rights to ./mvnw
          command: sudo chmod +x ./mvnw
      - run: ./mvnw clean install
      - run: ./mvnw test